# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81fbfdcdcfc693e8b4b94b8f0885924f50ac5c01b8f5dcfd7b103d4efd2c40bd5093efdcb8a52be6a02dcdae5c96d0e7849576b9f69288a6b738baa7c32e8563

test:
  secret_key_base: c43e3031fdc27417582d9d7240648a9430039e509f3fe1e525222d7708443590a577c39b9ce9334bb34dca15aa0f08f665db91fc79acaac45b2ab77f6a81e512

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
